---
- name: remediate from heartbleed
  hosts: all
  become: no
  gather_facts: no
  tasks:
    - name: reboot host
      shell: sleep 10 && /sbin/shutdown -r now
      async: 300
      poll: 0
      become: true
     - name: wait for the server to restart
       local_action: wait_for host={{ inventory_hostname }}
                     port=22
                     delay=30
                     timeout=300
                     state=started
                     connect_timeout=15
    - name: Check processes
      shell: >
        if [ "$(sudo lsof -n | grep ssl | grep DEL | wc -l)" != "0" ]; \
        then echo "We still have affected processes"; checkrestart; \
        exit 1; fi
    - name: wait for the server to restart
      local_action: wait_for host={{ inventory_hostname }}
                    port=22
                    delay=15
                    timeout=300
                    state=started
                    connect_timeout=15
